Repository ArweaveTeam/arweave, pull requests merged in 2018-09, with the labels that each got.

#54 Add check if block is in BHL for GET /block/(hash|height)/...
  src/ar_http_iface.erl
  src/ar_storage.erl
Labels: Priority: Normal, Status: Done, Type: Bug

#55 Fix pattern matching after default of block hash list has changed
  src/ar_node_utils.erl
Labels: Priority: Normal, Status: Done, Type: Bug

#59 Maintenance/slimline block validation
  src/ar_block.erl
  src/ar_mine.erl
  src/ar_node_utils.erl
Labels: Priority: Normal, Status: In Progress, Type: Maintenance

#62 Fix JSON struct to block when expect only transaction IDs
  src/ar_serialize.erl
Labels: Priority: Critical, Status: Done, Type: Bug

#64 Change Dockerfile to be based on Ubuntu 18.04
  Dockerfile
Labels: Priority: Normal, Status: Done, Type: Bug
